root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
rules:
  'prettier/prettier': error
  semi:
    - error
    - never
    - beforeStatementContinuationChars: always
  'simple-import-sort/imports':
    - error
    - groups:
      # Side effect imports.
      - ["^\\u0000"]
      # Import ECMAScript Abstract first.
      - ["^es-abstract"]
      # Packages.
      # Things that start with a letter (or digit or underscore), or `@` followed by a letter.
      - ["^@?\\w"]
      # Absolute imports and other imports such as Vue-style `@/foo`.
      # Anything not matched in another group.
      - ["^"]
      # Relative imports.
      # Anything that starts with a dot.
      - ["^\\."]
