name: Build Specification

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x 🟢
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install dependencies 📚
        run: npm ci
      - name: Build Specification ⚙
        run: npm run build:spec --if-present
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/spec
